const USER_ROLES = ["ADMIN", "DOCTOR"];

const DISEASE_STAGES = [
  "NON_DEMENTED",
  "VERY_MILD_DEMENTED",
  "MILD_DEMENTED",
  "MODERATE_DEMENTED",
];

const DIAGNOSIS_STATUS = [
  "SUSPECTED",
  "CONFIRMED",
  "UNDER_REVIEW",
  "RULED_OUT",
];

const CONSENT_TYPES = [
  "SCAN_SHARING",
  "INTER_BRANCH_ACCESS",
  "AI_TRAINING",
  "RESEARCH_USE",
];

const CONSENT_STATUS = ["GRANTED", "REVOKED", "EXPIRED", "PENDING"];

const ACCESS_ACTIONS = ["VIEW", "UPLOAD", "UPDATE", "DELETE", "DOWNLOAD"];

const ACCESS_STATUS = ["SUCCESS", "DENIED", "FAILED"];

const ROUND_STATUS = ["PENDING", "RUNNING", "COMPLETED", "FAILED"];

export {
  ACCESS_ACTIONS,
  ACCESS_STATUS,
  CONSENT_STATUS,
  CONSENT_TYPES,
  DIAGNOSIS_STATUS,
  DISEASE_STAGES,
  ROUND_STATUS,
  USER_ROLES,
};
